### ISSUE TITLE
Tables?

### ISSUE THREAD

**Issue by Addibro** [HansKre/sanity-plugin-html-to-portable-text#1]
Hello,

Can you edit/add tables here as well?

Thanks!

**Comment by HansKre** [comment]
Hello Andreas,

if you have a table as HTML then just paste it in and it will be turn out as portable text. 

Hope it's what you are looking for.

Cu, Hans

**Comment by Addibro** [comment]
Cool, I'll try it out, thanks!

**Comment by Addibro** [comment]
Hi again.

I have a "manualTable" type like this:

```javascript
export default {
  name: 'manualTable',
  type: 'object',
  fields: [
    {
      name: 'html',
      title: 'HTML to Table',
      type: 'htmlToProtableText',
    },
    {
      name: 'table',
      type: 'array',
      of: [ { type: 'block' } ]
    }
  ]
}
```

But when I open the editor in sanity i get:

"_Schema does not seem to specify a block-type. Please specify a valid block-type to see the output._"

What am I missing?

**Comment by HansKre** [comment]
I think, you are doing everything correctly, except for the type. It is a typo in the README. It should be `htmlToPortableText` instead of `htmlToProtableText`. Sorry for the inconvenience.

**Comment by Addibro** [comment]
We tried to change it to the correct spelling, but getting:
![image](https://user-images.githubusercontent.com/15065941/156150998-17b66f05-85e2-4394-8bda-14b55430c4a2.png)

**Comment by HansKre** [comment]
Apologies. Can you please update to version `0.0.6` and see if issue still exists?
