### ISSUE TITLE
issue with block-type

### ISSUE THREAD

**Issue by eede** [HansKre/sanity-plugin-html-to-portable-text#4]
Hi I have been trying to figure out what is the issue with block-type, I saw on another issue you mention this was a type, I had fixed that type but still having "Schema does not seem to specify a block-type. Please specify a valid block-type to see the output." issue, so below is the code I have for now. What am I missing, would you please let me know.

```
{ 
  name: 'htmlToArticleBody', 
  title: 'HTML content', 
  type: 'htmlToPortableText' , 
  options: { refblock: 'blockContent' }
},
{ name: "body", type: "blockContent", title: "Body" },
```

Edit: Actually it works when I place it to type document, but it doesn't work when i use it under subdocuments, or I don't know what they call this popup selectors

**Comment by HansKre** [comment]
Hi @eede, can you please let me know the plugin-version that you are using? Thanks.

**Comment by eede** [comment]
> Hi @eede, can you please let me know the plugin-version that you are using? Thanks.

it is 0.0.6

When I use it on the global page, not in the array it works, but when I use it inside the array when it populates a popup to add content, it doesn't work

**Comment by eede** [comment]
> Hi @eede, can you please let me know the plugin-version that you are using? Thanks.

I guess it is something related to sanityDocument, but I'm not too familiar with how to get it.

**Comment by rmorgan-supernatural** [comment]
@HansKre I'm having a similar problem, same error as @eede 
Below is how I have it set up and I'm also getting "Schema does not seem to specify a block-type. Please specify a valid block-type to see the output." Attached is a screen of what things looks like in Sanity Studio.

`  fields: [
    {
      title: 'Question',
      name: 'Question',
      type: 'string'
    },
    {
      name: 'htmlToArticleBody',
      title: 'HTML to Article Body!',
      type: 'htmlToPortableText',
      options: { refblock: 'answer' }
    },
    {
      name: 'answer',
      title: 'Answer',
      type: 'array',
      of: [ { type: 'block' } ]
    }
  ],`

![image](https://user-images.githubusercontent.com/94861394/163460560-7e12c681-fe3f-4549-aebe-a555cf8564d7.png)

**Comment by HansKre** [comment]
Hello @rmorgan-supernatural, I couldn't reproduce the issue:

`htmlToPortableTextIssue.js`:

```js
/* eslint-disable import/no-anonymous-default-export */
export default {
  name: 'htmlToPortableTextIssue',
  title: 'Issue #4 Test',
  type: 'document',
  fields: [
    { title: 'Question', name: 'Question', type: 'string' },
    {
      name: 'htmlToArticleBody',
      title: 'HTML to Article Body!',
      type: 'htmlToPortableText',
      options: { refblock: 'answer' },
    },
    { name: 'answer', title: 'Answer', type: 'array', of: [{ type: 'block' }] },
  ],
};
```

`schema.js`:
```js
import createSchema from 'part:@sanity/base/schema-creator';
import schemaTypes from 'all:part:@sanity/base/schema-type';

import htmlToPortableTextIssue from './htmlToPortableTextIssue';

export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    htmlToPortableTextIssue,
  ]),
});
```

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/7346919/166195771-83921be2-17bc-4b07-bfdf-7e533fcf773b.png">

Can you please provide more info to help me reproduce?

**Comment by HansKre** [comment]
@eede 

If you look at the documentation, you only need to specify the `refblock` if there are multiple of them. In your case, it is not needed. But if you still want to do it, then you need to provide proper name, so in your case it would be `options: { refblock: 'body' }`.

> ```
> { 
>   name: 'htmlToArticleBody', 
>   title: 'HTML content', 
>   type: 'htmlToPortableText' , 
>   options: { refblock: 'body' }
> },
> { name: "body", type: "blockContent", title: "Body" },
> ```

**Comment by 3200pro** [comment]
HI @HansKre 

I think the reason why you couldn't reproduce the issue @rmorgan-supernatural was having is because he's got his block type one level down.

In your testing the block type is at the same level as `htmlToPortableText`

Something along the lines of blockContent.block seems to be what's needed. It doesn't seem like the plugin recognizes the array 1 level into another object


```
{
      name: "htmlToArticleBody",
      title: "HTML to Article Body",
      type: "htmlToPortableText",
      options: { refblock: "blockContent.block" }
    },
```

**Comment by rmorgan-supernatural** [comment]
@3200pro @HansKre That looks to be the issue. I'm no Sanity expert and inherited this project from someone else but the way it's set up is I have document level schema the loads another schema of objects, the main one being one called "pagebuilder" that is a set of specific content block types like faq or hero.

In this case its something like document -> pageBuilder -> faqContent

If that makes sense is there an easy enough workaround to make the reference work?

**Comment by doublejosh** [comment]
**This issue is still real and shouldn't be closed.**

The plugin doesn't work with named PortableText object type fields... **it only works with inline definitions**, which isn't a great/scalable way to manage your text editor schema.

Pretty please re-open. Thanks.

**Comment by doublejosh** [comment]
@HansKre ☝️  ...please open. Thanks.

**Comment by HansKre** [comment]
This shall have my top prio. Will try to fix as soon I am available. Sorry for all the inconveniences.

**Comment by HansKre** [comment]
@3200pro Can you please provide full schema?
As I pointed out in [this comment ](https://github.com/HansKre/sanity-plugin-html-to-portable-text/issues/4#issuecomment-1114571887), issue from @eede is not with nesting.

In his example:

```
{ 
  name: 'htmlToArticleBody', 
  title: 'HTML content', 
  type: 'htmlToPortableText' , 
  options: { refblock: 'blockContent' }
},
{ name: "body", type: "blockContent", title: "Body" },
```

He is providing name `blockContent` which is nowhere defined. What he should do is to reference the name of the `blockContent`-type, which is `body` in his case.

With the above info, I'm afraid it seems like there's nothing wrong with the plugin. If you provide a full schema example, I can have a look again.

**Comment by HansKre** [comment]
Tried to reproduce @rmorgan-supernatural's issue:
> fields: [ { title: 'Question', name: 'Question', type: 'string' }, { name: 'htmlToArticleBody', title: 'HTML to Article Body!', type: 'htmlToPortableText', options: { refblock: 'answer' } }, { name: 'answer', title: 'Answer', type: 'array', of: [ { type: 'block' } ] } ],

Using following setup:

`htmlToPortableTextTest.js`

```js
/* eslint-disable import/no-anonymous-default-export */
export default {
  name: 'htmlToPortableTextTest',
  title: 'Test of Html-to-Portable-Text Plugin',
  type: 'document',
  fields: [
    { title: 'Question', name: 'Question', type: 'string' },
    {
      name: 'htmlToArticleBody',
      title: 'HTML to Article Body!',
      type: 'htmlToPortableText',
    },
    {
      name: 'answer',
      title: 'Answer',
      type: 'array',
      of: [{ type: 'block' }],
    },
  ],
};

```

`schema.js`

```js
import createSchema from 'part:@sanity/base/schema-creator';
import schemaTypes from 'all:part:@sanity/base/schema-type';

import htmlToPortableTextTest from './htmlToPortableTextTest';

export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    htmlToPortableTextTest,
  ]),
});
```

Result

<img width="955" alt="image" src="https://user-images.githubusercontent.com/7346919/179043229-a1df332a-02b8-4b8e-af08-a3fa444016af.png">

**Comment by rmorgan-supernatural** [comment]
@HansKre Here's the full schema I was using. I think my company is probably moving away from Sanity but if this can help someone else happy to continue assisting and confirm any fixes.

export default {
  title: 'FAQ',
  name: 'faqBlock',
  type: 'object',
  icon: List,

  fields: [
    {
      title: 'Internal Name',
      name: 'internalName',
      type: 'string'
    },
    {
      title: 'Headline',
      name: 'headline',
      description: 'Title for this group of FAQ questions',
      type: 'string'
    },
    {
      title: 'Question and Answers',
      name: 'faqContent',
      type: 'array',
      of: [{ type: 'faqContent' }],
      description: 'These are the questions and answers for this group of FAQ questions',
      validation: Rule => Rule.required().min(1)
    }
  ],

**Comment by HansKre** [comment]
@rmorgan-supernatural I can't see a `type: 'htmlToPortableText',` field.
Also, I get a `Unknown type: faqContent.` error when trying to run your schema.

**Comment by rmorgan-supernatural** [comment]
Oh crap, copied the production schema I'm currently using because I couldn't get the plugin to do what I needed.  This sanity project is something I inherited and as broken down into discreet components so I might not be of much use but let me dig around and see if I can find an older version of this that was still using your plugin.

**Comment by doublejosh** [comment]
Perhaps I could help test? I'm still running this plugin in our main prod instance.
