### ISSUE TITLE
Non-breaking space (U+00A0)

### ISSUE THREAD

**Issue by doublejosh** [HansKre/sanity-plugin-html-to-portable-text#5]
The HTML input fails if the source has a `U+00A0` non-breaking space character included. I assume other folks also copy paste things into this field that may include such characters.

Perhaps there's a way to create a block that's just this one character in order to swallow the input, but I double it.

Seems reasonable to drop that type of gremlin.

**Comment by HansKre** [comment]
@doublejosh thanks for reporting the issue. The `U+00A0` could be converted to a regular space in portable text. Would that be the expected behavior?

<img width="624" alt="image" src="https://user-images.githubusercontent.com/7346919/179390214-8b3da948-53a2-45a7-b8af-dadc699db33f.png">

**Comment by HansKre** [comment]
Fix is available in latest release. @doublejosh please let me know if this issue can be closed.
