### ISSUE TITLE
How to set type "htmlToPortableText" when posting from API?

### ISSUE THREAD

**Issue by gizzidan** [HansKre/sanity-plugin-html-to-portable-text#7]
_I have a minor issue I was hoping you could assist with._

One of my use cases for this is to be able to create documents from form data sent via API. My issue when the form data for this html field is sent to the "htmlToDescription" field it is being sent as type "string." I looked through the source code, but can't find the structure needed to send it as type "htmlToPortableText."

I ran into a similar issue with the "slug" fields where it was sending as "string" instead of the required type "slug." The solution for that was simply to create quick object for type "slug." I was able to find the structure just by viewing it via GROQ in Sanity Vision. However, I can't do that with this because the field isn't actually saved: 
```
const slug = {
   _type: "slug",
   current: tagName,
};
const newTag = {
   _id: tag[0] && tag[0]._id ? tag[0]._id : `drafts.${tagName}`,
   _type: "jobTag",
   tagName: tagName,
   slug: slug,
};
```

![image](https://user-images.githubusercontent.com/16409212/198897376-d1503525-2a87-4772-ae4e-b235d7595f52.png)

**Comment by HansKre** [comment]
Hi @gizzidan , thank you for using `thmlToPortableText`-plugin.
You might want to have a look at [handleHtmlChange](https://github.com/HansKre/sanity-plugin-html-to-portable-text/blob/f0d150d245ba7492747ae52cd58d01d8018c72b3/src/index.tsx#L70). You'll notice that only the html-string is needed as input.

Ultimately, [`convertToBlock`](https://github.com/HansKre/sanity-plugin-html-to-portable-text/blob/f0d150d245ba7492747ae52cd58d01d8018c72b3/src/htmlUtils.ts#L32) gets called with nothing but the html-string and the `blockContentType`.

You can think of the `blockContentType` as the style-definition or in other words it tells the [`@sanity/block-tools`](https://www.npmjs.com/package/@sanity/block-tools)-converter how to go from `html` to `portable-text`.

> blockContentType
A compiled version of the block content schema type. When you give this option, the deserializer will respect the schema when deserializing to blocks. I.e. if the schema doesn't allow h2-styles, all h2 html-elements will deserialized to normal styled blocks.

Example:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/7346919/199042756-83c1e838-bd61-4abe-a076-33155d14bc76.png">

Here's an example how to [`compileBlockContentType`](https://github.com/HansKre/sanity-plugin-html-to-portable-text/blob/f0d150d245ba7492747ae52cd58d01d8018c72b3/src/schemaUtils.ts#L40)

Does this answer your question?

**Comment by gizzidan** [comment]
It helped a bit, I was able to use parts of the code to figure out how to convert the html to portable text before sending via API. It seems that this plugin only works when entering direct through the Sanity studio. I think the API doesn't work with it because the field is not actually stored. Regardless, I was able to figure it out! Thanks!
